@host = http://localhost:3000

### 
GET {{host}}/api/posts

###
POST {{host}}/api/posts
Content-Type: application/json

{
  "title": "Diseño de bases de datos relacionales",
  "description": "Claves primarias, foráneas y normalización.",
  "category": "database",
  "author_id": 3
}

###
GET {{host}}/api/authors

###
POST {{host}}/api/authors
Content-Type: application/json

{
  "name": "Juan",
  "email": "juan@email.com",
  "image": "https://example.com/juan.jpg"
}

###
GET {{host}}/api/authors/1/posts
